-- Coloque scripts iniciais aqui
CREATE TABLE IF NOT EXISTS CLIENTE (
    ID INT PRIMARY KEY,
    SALDO INT NOT NULL,
    LIMITE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACAO (
    ID INT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL REFERENCES CLIENTE(ID),
    TIPO CHARACTER(4) NOT NULL,
    VALOR INT NOT NULL,
    DESCRICAO VARCHAR(10) NOT NULL,
    REALIZADA_EM TIMESTAMP NOT NULL
);

INSERT INTO CLIENTE VALUES
    ('1', '100000', '0'),
    ('2', '80000', '0'),
    ('3', '1000000', '0'),
    ('4', '10000000', '0'),
    ('5', '500000', '0');